add_subdirectory(utils/logger)
add_subdirectory(client)
add_subdirectory(signupserver)
add_subdirectory(metaserver)
add_subdirectory(authentication_server)
add_subdirectory(notification_server)
add_subdirectory(data_blockserver)
add_subdirectory(meta_blockserver)
# password_db contains only scripts, no CMake target needed.

